title: Solofront
author:
  name: Nerijus Gudas
  email: 'nerijus@solofront.com'
blog:
  route: ''
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
taxonomies: [category,tag,month]
